name: Release new version

#on:
#  release:
#    types: [published]

on:
  push:
    branches: [master]

env:
  ONTOLOGY_NAME: manufacturing

permissions:
  contents: write

jobs:
  release_version:
    #concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - env:
          TAG: ${{ github.ref_name }}

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: List tag
        run:
          tag1="${TAG}"
          tag2="${GITHUB_REF#refs/tags/}"
          version=${TAG#v}
          echo "ref_name: $TAG"
          echo "tag: ${GITHUB_REF#refs/tags/}"
          echo "tag1: $tag1"
          echo "tag2: $tag2"
          echo "version: $version"
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}"
          echo "VERSION=$VERSION"


          #mkdir -p versions/$version
          #cp -f \
          #    README.md +
          #    ${ONTOLOGY_NAME}.ttl \
          #    ${ONTOLOGY_NAME}-dependencies.ttl \
          #    ${ONTOLOGY_NAME}-inferred.ttl +
          #    versions/$version/.

      #- name: Push to gh-pages
      #  run:
      #    git add versions/$version
      #    git commit -m "Release version $version"
      #    git push origin gh-pages
