name: Release new version

on:
  release:
    types: [published]

env:
  ONTOLOGY_NAME: manufacturing
  TAG: ${{ github.ref_name }}

permissions:
  contents: write

jobs:
  release_version:
    #concurrency: ci-${{ github.ref }}  # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Create and copy generated files to versions/
        run: |
          mkdir -p versions/${TAG#v}
          cp -f \
              README.md \
              ${ONTOLOGY_NAME}.ttl \
              ${ONTOLOGY_NAME}-dependencies.ttl \
              ${ONTOLOGY_NAME}-inferred.ttl \
              versions/${TAG#v}/.

      - name: Push to gh-pages
        run: |
          git add versions/${TAG#v}
          git commit -m "Release version ${TAG#v}"
          git push origin gh-pages
